# Generated by Django 2.2.2 on 2019-06-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barbarian', models.CharField(max_length=30)),
                ('bard', models.CharField(max_length=30)),
                ('cleric', models.CharField(max_length=30)),
                ('druid', models.CharField(max_length=30)),
                ('fighter', models.CharField(max_length=30)),
                ('monk', models.CharField(max_length=30)),
                ('paladin', models.CharField(max_length=30)),
                ('ranger', models.CharField(max_length=30)),
                ('rogue', models.CharField(max_length=30)),
                ('sorcerer', models.CharField(max_length=30)),
                ('wizard', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dwarf', models.CharField(max_length=30)),
                ('elf', models.CharField(max_length=30)),
                ('gnome', models.CharField(max_length=30)),
                ('halfelf', models.CharField(max_length=30)),
                ('halforc', models.CharField(max_length=30)),
                ('halfling', models.CharField(max_length=30)),
                ('human', models.CharField(max_length=30)),
            ],
        ),
    ]
