# Generated by Django 2.2.2 on 2019-06-14 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pg1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('race', models.CharField(max_length=50)),
                ('classes', models.CharField(max_length=50)),
                ('strength', models.IntegerField()),
                ('dexterity', models.IntegerField()),
                ('constitution', models.IntegerField()),
                ('intelligence', models.IntegerField()),
                ('wisdom', models.IntegerField()),
                ('charisma', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='classes',
            name='barbarian',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='bard',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='cleric',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='druid',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='fighter',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='monk',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='paladin',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='ranger',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='rogue',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='sorcerer',
        ),
        migrations.RemoveField(
            model_name='races',
            name='dwarf',
        ),
        migrations.RemoveField(
            model_name='races',
            name='elf',
        ),
        migrations.RemoveField(
            model_name='races',
            name='gnome',
        ),
        migrations.RemoveField(
            model_name='races',
            name='halfelf',
        ),
        migrations.RemoveField(
            model_name='races',
            name='halfling',
        ),
        migrations.RemoveField(
            model_name='races',
            name='halforc',
        ),
    ]
